### ISSUE TITLE
A file is missing

### ISSUE THREAD

**Issue by zhangpicb** [weng-lab/ENCODE-cCREs#2]
Hi,

Step 1 - filter and process DHSs need calcuate.zscore.py,but version2 don't have this script.And 1_Process-DHSs.sh line39 
``` python $scriptDir/calculate.zscore.sh out.tab | sort -k1,1 > 1 ``` may have some error.

Thanks!

**Comment by Jill-Moore** [comment]
The [script](https://github.com/weng-lab/ENCODE-cCREs/blob/master/Version-2/cCRE-Pipeline/Scripts/calculate.zscore.sh) is now available
