### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by zhangpicb** [weng-lab/ENCODE-cCREs#3]
Hi @Jill-Moore ,

Thanks for your wonderful figures and code.
I want to learn how to output similar picture.There are some files are missing.cCRE-Analysis file folder,Supplementary Figure 10 , doesn't contain ***Conservation-Meta-cCRE.sh*** and ***Conservation-Meta-cCRE-Single.sh***.

Thanks very much !

**Comment by Jill-Moore** [comment]
Thank you for bringing this to our attention. I have uploaded the missing scripts to the repo:

https://github.com/weng-lab/ENCODE-cCREs/blob/master/Version-2/cCRE-Analysis/Scripts/Conservation-Meta-cCRE.sh
https://github.com/weng-lab/ENCODE-cCREs/blob/master/Version-2/cCRE-Analysis/Scripts/Conservation-Meta-cCRE-Single.sh

**Comment by zhangpicb** [comment]
Hi @Jill-Moore ,

Thanks very much for your reply.But there are still some files are missing.
I can't find the ***per-bp.py*** in Conservation-Meta-cCRE.sh and ***process-gerp.py*** in Supplementary-Figure-10a.cCRE-GERP-Overlap.sh.

Thanks very much !

**Comment by Jill-Moore** [comment]
updated!
