### ISSUE TITLE
about GRCh38-cCREs.bed

### ISSUE THREAD

**Issue by JingGuo1997** [weng-lab/ENCODE-cCREs#6]
Hi,developer
Thanks for your resource！And after downloading the file GRCh38-cCREs.bed, I found that it has 6 columns. However, I cannot find information about what the fourth column represents mean，like “EH38D4327509”.

<img width="498" alt="image" src="https://github.com/weng-lab/ENCODE-cCREs/assets/84696797/b1139c79-a9a8-4571-b0f7-768f4037aeb7">
Sincerely looking forward to your reply.

**Comment by Jill-Moore** [comment]
Thank you for your interest in the cCREs. In the particular file you linked the columns are defined as follows:

col 1 - Chrom
col 2 - Start
col 3 - End
col 4 - rDHS ID
col 5 - cCRE ID
col 6 - cCRE group

**Comment by JingGuo1997** [comment]
> Thank you for your interest in the cCREs. In the particular file you linked the columns are defined as follows:
> 
> col 1 - Chrom col 2 - Start col 3 - End col 4 - rDHS ID col 5 - cCRE ID col 6 - cCRE group

This is very helpful to me. Thank you for your response.

**Comment by Jill-Moore** [comment]
Great!
